//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centrilux.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chofer
    {
        public int Chofer_ID { get; set; }
        public int Persona_ID { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> Fecha_ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_egreso { get; set; }
    }
}
