//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centrilux.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro
    {
        public int Seguro_ID { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha_pago { get; set; }
        public Nullable<int> Importe { get; set; }
        public string Comentarios { get; set; }
    }
}
