//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centrilux.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int Turno_ID { get; set; }
        public int Movil_ID { get; set; }
        public string Comentarios { get; set; }
    }
}
